import { Container } from '~/components/primitives/Container'
import { Content } from '~/components/shared/Content'
import { Breadcrumb } from '~/components/shared/Breadcrumb'
import { Link } from '~/components/primitives/Link'
import { styled } from '~/styles/stitches.config'

const H1 = styled('h1', {
  mb: '$regular',
  mt: '$large',
  textAlign: 'center',
  '@regular-min': {
    mb: '$large',
    mt: '$x-large',
    textAlign: 'left',
  },
})

export const Terms = () => {
  return (
    <Container css={{ pb: '$xx-large' }}>
      <Breadcrumb path={[{ url: '/', label: 'Home' }, { label: 'Terms of Service' }]} />
      <H1>Terms of Service</H1>
      <Content>
        <p><strong>RareMint Terms of Service</strong></p>
        <p><strong>Last Revised: March 10, 2022</strong></p>
        <p>RareMint Limited (“RareMint,” “we,” “us,” or “our”), a British Virgin Islands company, operates the website RareMint.com (the “Site”) and RareMint NFT platform (the “Platform”), which provide users with the opportunity to purchase, collect, and showcase non-fungible tokens or similar digital items implemented on a blockchain (“NFTs”) that reference physical and digital sports memorabilia and artworks (collectively, the “Services”). Your use of the Services is expressly conditioned upon your acceptance of and adherence to these Terms of Service (“Terms”), the RareMint Privacy Policy (the terms of which are incorporated herein by reference), and all applicable laws and regulations in your jurisdiction of residence.</p>
        <p>The Services are intended for use by adults who have reached the age of majority in the jurisdiction in which the reside. Minors who are at least 13 years of age are only permitted to use the Services if the minor's parent/guardian accepts these Terms on the minor's behalf prior to using the Services. Children under the age of 13 are not permitted to use the Services.</p>
        <p>THESE TERMS ARE A BINDING LEGAL AGREEMENT BETWEEN THE USER (“YOU” OR “YOUR”) AND RAREMINT. BY USING THE SERVICES OR ANY PART OF THEM, BY MAKING A PURCHASE ON THE PLATFORM, AND/OR BY CLICKING “I ACCEPT” BELOW, YOU ARE CONFIRMING THAT (1) YOU (A) ARE OF LEGAL AGE AND COMPETENT TO ENTER INTO CONTRACTS IN THE JURISDICTION IN WHICH YOU RESIDE, OR (B) ARE AT LEAST 13 YEARS OF AGE AND HAVE PARENT/GUARDIAN CONSENT TO USE THE SERVICES; AND (2) YOU UNDERSTAND AND AGREE TO BE BOUND BY ALL OF THESE TERMS. IF YOU ARE ACCEPTING THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO ACCEPT THESE TERMS ON THAT ENTITY'S BEHALF, IN WHICH CASE “YOU” WILL MEAN THE ENTITY. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU CANNOT OR DO NOT ACCEPT ALL OF THESE TERMS, PLEASE DISCONTINUE USE OF THE SERVICES IMMEDIATELY.</p>
        <strong>These Terms contain an arbitration clause and class action waiver that affect your legal rights (Section 19). By agreeing to these Terms, you agree (A) to resolve all disputes with us related to the Services through binding individual arbitration, which means that you waive any right to have those disputes decided by a judge or jury, and (B) to waive your right to participate in class actions, class arbitrations, or representative actions in connection with your use of the Services. You have the right to opt out of arbitration as explained in Section 19.</strong>
        <h3>1. ACCESS TO AND USE OF THE SERVICES.</h3>
        <ol>
          <li>Provided that you accept and comply with these Terms, RareMint grants you a limited, non-exclusive, non-commercial, non-transferrable, and non-sublicensable right and license to access, use, and display the Services, including any software, content, and materials provided to you as part of the Services, in each case for the sole purpose of enabling you to use the Services as permitted by these Terms.</li>
          <li>You are responsible for obtaining any computer equipment or mobile device and networking access, and any consents or permissions, you need to access and use the Services and for all associated costs.</li>
          <li>
            In consideration of RareMint allowing you to use the Services, you represent and warrant to RareMint and agree that:
            <ol>
              <li>You are the exclusive beneficiary and/or legal owner of any cryptocurrency used or intended to be used for the purchase of any Collectible or digital asset on the Services;</li>
              <li>You will not hide or disguise the IP address of the mobile device or computer you use to access the Services or otherwise take actions that interfere with us correctly identifying the IP address associated the physical location from which your mobile device or computer accesses the Internet.</li>
              <li>Your use of the Services will not violate any laws or regulations of any jurisdiction whose laws or regulations apply to you;</li>
              <li>You are not a resident of a country that is subject to embargo by the United States or that the United States has designated as a “terrorist supporting” country, nor on any list of prohibited or restricted parties maintained by the United States;</li>
              <li>You have not been identified as a Specially Designated National or placed on any sanctions list by the U.S. Treasury Department's Office of Foreign Assets Control, the U.S. Commerce Department, or the U.S. Department of State; and you will not use our Website to conduct any illegal or illicit activity;</li>
              <li>You have not been placed on any of the following lists: European External Action Service Consolidated Financial Sanctions List; EU Terrorist List; FATF Non-Cooperative Countries and Territories; Federal Bureau of Investigation Most Wanted Terrorists & Seeking Information; Bank of England Sanctions List; HM Treasury Sanctions List; Politically Exposed People List; World Bank Ineligible Firms; Department of Foreign Affairs and Trade Consolidated List;</li>
              <li>You will not export or re-export, directly or indirectly, the Services, the NFTs and/or other information or materials provided by RareMint hereunder, to any country for which the United States or any other relevant jurisdiction requires any export license or other governmental approval at the time of export without first obtaining such license or approval; and</li>
              <li>You will not reproduce, display, distribute, or create derivative works of any Collectible, including but not limited to any physical items associated with an NFT.</li>
            </ol>
          </li>
          <li>Any violation of these Terms will immediately terminate your license to access and use the Services and may subject you to legal action. If you would like to use the Services in a way that exceeds the scope of this license, please contact us for permission.</li>
        </ol>
        <h3>2. USER ACCOUNTS.</h3>
        <ol>
          <li>You may be required to create an account to the Services, to save your preferences or activity history, or to complete a transaction on the Platform. In that event, you will use your account for your internal use only.</li>
          <li>In creating an account, you must provide accurate and complete registration information to create an account on the Services. We reserve the right to disable any log-on ID, at any time and in our sole discretion, if you fail to comply with or attempt to circumvent any of the account registration requirements. You may not impersonate someone else, create an account for anyone other than yourself, provide an email address or blockchain address other than your own, or create multiple accounts.</li>
          <li>If you choose, or you are provided with, a log-on ID (such as a username and password or, another identifier) as part of our security procedures, you must treat such information as confidential and must not reveal it to anyone else. Our use of your personal information will be governed by our Privacy Policy <Link to="/terms-of-service">"PRIVACY POLICY"</Link>, which is incorporated into these Terms by reference.</li>
          <li>By disclosing your email address and/or mobile telephone number to create an account, you agree that we may contact you for the purpose of advising you of changes or additions to the Services, about any of our products or services, or for such other purpose(s) as we deem appropriate. You may opt out of these communications at any time by following the unsubscribe instructions provided in the communication. Your consent to receive promotional emails, messages, and calls is not required to use the Platform, and you may limit or revoke your consent at any time by contacting us a support@raremine.com. RareMint is not responsible for any telecommunications fees you incur from any emails, messages, or calls or from your use of the Services.</li>
          <li>You are solely responsible for maintaining the confidentiality of your account information (i.e., user ID, password and/or challenge questions). You are also responsible for all activities that occur in connection with your account, irrespective of whether you personally engage in such activities. RareMint has no responsibility, and will not be liable in any way, for anything done via your account or using your password (including any unauthorized uses by third parties), such as the sale or transfer or your purchased NFTs. You agree to notify us immediately in the event of any known or suspected unauthorized use of your user account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of your password.</li>
        </ol>
        <h3>3. USER CONTENT.</h3>
        <ol>
          <li>If and to the extent you are permitted to and do submit any comments, ratings, reviews, chats, customer service inquiries, or other content to be posted on the Site or on the Platform (“User Content”), you grant RareMint a perpetual, non-exclusive license to use, reproduce, distribute, display, modify, create derivative works of, and sublicense the User Content in any way, including but not limited to reposting that User Content on the Site. This license extends to your first name and your username and profile information (if applicable). All of your communications with us through personal accounts or otherwise, as well as any attachments to those communications or otherwise submitted to us (such as documents, photographs and videos) are User Content.</li>
          <li>RareMint shall be free to use any ideas, concepts, know-how, or techniques contained in your User Content for any purpose whatsoever, including but not limited to, the development, production, and marketing of products and services that incorporate such information without compensation or attribution to you.</li>
          <li>RareMint have the right, but not the obligation, to review, refuse to display, or remove any User Content for any reason, at ours sole discretion.</li>
        </ol>
        <h3>4. PROHIBITED USES OF THE SERVICES.</h3>
        <ol>
          <li>
            You may only use the Platform for lawful purposes, in a responsible manner, and in a way that does not damage our name or reputation or that of any of our affiliates, directors or officers, or any of the creators. By way of example and not limitation, you may not use the Services to:
            <ol>
              <li>access or attempt to access another user's account without his or her consent;</li>
              <li>abuse, stalk, threaten, or otherwise harass another Services user or employee or representative of RareMint (including, without limitation, submitting false or excessive customer service requests, refusing to follow the instructions of a RareMint employee or representative, or publicly disparage a RareMint employee or representative);</li>
              <li>impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with RareMint or any other person or entity;</li>
              <li>solicit, collect or post personal data or attempt to solicit, collect or post personal data about other users of the Services, including user names or passwords;</li>
              <li>
                submit User Content that
                <ol>
                  <li>is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, sexually explicit, libelous, fraudulent, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable (in our sole discretion);</li>
                  <li>promotes or encourages illegal activity, self-harm, violence, exploitation, doxxing, or other harmful acts;</li>
                  <li>infringes in any manner on the copyright, trademark or other intellectual property rights of any person or entity, or that contains any confidential or proprietary information of any person or entity, or that otherwise violates the legal rights of any person or entity, including but not limited to by claiming a RareMint username for the purpose of reselling it or otherwise engage in name squatting;</li>
                  <li>contains or comprises any viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature; or</li>
                  <li>constitutes unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of commercial solicitation;</li>
                </ol>
              </li>
              <li>interfere with or attempt to interrupt the proper operation of the Services through the use of any software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
              <li>reverse engineer, decompile, data mine, record, "scrape," link to, collect information or otherwise manipulate content from any portion of the Services; provided, however, we grant the operators of public search engines permission to use spiders to copy materials from the public portions of the Site for the sole purpose of, and solely to the extent necessary for, creating publicly-available searchable indices of the materials, but not caches or archives of such materials;</li>
              <li>resell or attempt to resell the Services;</li>
              <li>use the Service to collect information or market research for a competing business;</li>
              <li>remove or attempt to remove, modify or disable any digital rights management feature of the Services or any copyright, trademark, patent, confidentiality, or other proprietary rights notice associated with the Services;</li>
              <li>use, employ, or operate bots, scripts, or other automated tools to perform any action on the Platform, including but not limited to registration of user names, purchase of Collectibles, and/or submitting User Content;</li>
              <li>take any action that that does or could (in our sole discretion) damage, disable, overburden, or impair the functioning of the Services in any manner;</li>
              <li>access the Services from a different blockchain address if we've blocked any of your other blockchain addresses from accessing the Service, unless you have our written permission first;</li>
              <li>take any other action or otherwise interact with the Services or its users in a way that is likely to disrupt the use and enjoyment of the Services by other Users; or</li>
              <li>solicit, encourage or assist any party in taking any of the foregoing actions (each a “Prohibited Activity”).</li>
            </ol>
          </li>
          <li>If you engage in any of the Prohibited Activities, we may, at our sole and absolute discretion, without notice or liability to you, and without limiting any of our other rights or remedies at law or in equity, (A) immediately limit, suspend or terminate your access to the Services; and (B) declare void any Collectibles transaction that was completed with the assistance of, as a result of, and/or in connection with such Prohibited Activities.</li>
        </ol>
        <h3>5. DIGITAL WALLETS AND CURRENCY.</h3>
        <ol>
          <li>The Services are built on top of the Ethereum network, but the Services may use other decentralized blockchain-based protocols instead of or as well as Ethereum, or forks of Ethereum or other such protocols. References in these Terms to Ethereum should be deemed to also refer to any other protocol we use.</li>
          <li>Users can only make purchases using the cryptocurrency Ethereum (“ETH”). We may update the cryptocurrency you can use to buy collectibles from time to time at our sole discretion.</li>
          <li>You must associate a compatible non-custodial wallet (e.g., a MetaMask wallet) (“External Wallet”) with your account in order to purchase, store and engage in transactions using the interface provided by the Platform. More information may be provided in the specific terms and conditions of an individual drop. We may update the range of compatible wallets from time to time at RareMint's sole discretion.</li>
          <li>
            By using an External Wallet in connection with the Services, you agree that you are using such External Wallet under the terms and conditions of the applicable providers of such External Wallet. (For example, for the MetaMask wallet, those terms and conditions are available at <a href="https://metamask.io/terms.html">https://metamask.io/terms.html</a>.)
            <ol>
              <li>External Wallets are not operated by, maintained by, supported by, or affiliated with RareMint.</li>
              <li>RareMint does not have custody or control over the contents of your wallet, and the private keys necessary to decrypt an External Wallet are held solely by you. RareMint has no ability to help you access or recover your private keys for your External Wallet.</li>
              <li>RareMint accepts no responsibility or liability to you in connection with your use of a External Wallet, and makes no representations or warranties regarding how the Services will operate with any specific External Wallet. If you discover an issue related to your External Wallet, please contact your wallet provider.</li>
            </ol>
          </li>
          <li>You are solely responsible for keeping your wallet secure and you should never share your wallet credentials or seed phrase with anyone. RareMint is not liable for any acts or omissions by you in connection with your External Wallet or as a result of your External Wallet being compromised. You agree to notify RareMint promptly upon discovering that your External Wallet has been compromised.</li>
          <li>RareMint reserves the right to refuse to associate an External Wallet with a User's Account in its sole and exclusive discretion. If you attempt to associate your Account with a Non-Custodial Wallet bearing risk factors, such attempts may result in the suspension or termination of your Account, each as determined in RareMint's sole and exclusive discretion. If you decide to transfer an asset, RareMint accepts no liability or responsibility for any such transfer, including for any loss, data corruption, or other negative impact that may occur to your NFTs or wallets or other assets when attempting to transfer assets between wallets.</li>
        </ol>
        <h3>6. DIGITAL WALLETS AND CURRENCY.</h3>
        <ol>
          <li>
            Through the RareMint Services, you may be permitted to purchase buy and own collectible NFTs created by RareMint that are (a) connected to the corresponding physical asset held in our vault (“Asset-Backed NFTs”), or (b) digital-only editions (“Digital-Only NFTs”) (each a “Collectible”).
            <ol>
              <li>NFTs will be minted by RareMint on the blockchain specified by RareMint and stored and managed within a RareMint custodial wallet until purchased.</li>
              <li>RareMint will list, or “drop,” new Collectibles on the RareMint marketplace, where users can then purchase the Collectibles exclusively on the Services.</li>
            </ol>
          </li>
          <li>
            Asset-Backed NFTs. Asset-Backed NFTs are digital tokens that represent ownership of a physical item of sports memorabilia (each a “Physical Asset”).
            <ol>
              <li>When you purchase an Asset-Backed NFT at RareMint, you acquire sole ownership of the associated Physical Asset. Each Physical Asset will be held in custody at RareMint's secure vault unless or until the purchaser redeems the Asset-Backed NFT in accordance with this Section 6.2.</li>
              <li>Vault services are currently provided at no additional cost. Vault services include placement in our secure vault, insurance and proper storage inside the vault in such a manner as to protect it from damage, loss, or theft, using a commercially reasonable degree of care.</li>
              <li>
                At any time, you may notify RareMint in writing of your election to redeem the Asset-Backed NFT for possession of the Physical Asset.
                <ol>
                  <li>Upon such election, the Asset-Backed NFT is returned to RareMint and “burned.”</li>
                  <li>The Physical Asset will be removed from the RareMint vault, packed, and shipped to you, at your cost, using a commercially-reasonable shipping service and insurance.</li>
                  <li>You are solely responsible for payment of any tax that may be due upon shipment of the Physical Asset, which may include, without limitation, sales, use, value-added and other taxes, duties and assessments on any sales or other similar tax that may be due as set forth by RareMint.</li>
                </ol>
              </li>
              <li>You agree that you will not attempt to sell a Physical Asset other than by selling the associated Asset-Backed NFT, unless you first elect to redeem the Asset-Backed NFT for the Physical Asset.</li>
            </ol>
          </li>
          <li>Digital-Only NFTs. Digital-Only NFTs may comprise a digital artwork created or licensed by RareMint or may grant the NFT holder rights to obtain certain additional products or services, such as unlocking a reward or access to an exclusive event.</li>
          <li>Additional rights in Collectibles are limited by and subject to the rights set forth in the Content License described in Section 9.</li>
        </ol>
        <h3>7. PURCHASING COLLECTIBLES.</h3>
        <ol>
          <li>
            The Platform provides users with a convenient interface that allows users to offer for sale, sell and buy Collectibles (each a “Transaction”). RareMint will be the initial seller of each Collectible, and the first Transaction relating to a Collectible will be between RareMint and the initial purchaser. Subsequent Transactions relating to such Collectible will be directly between users.
            <ol>
              <li>When you purchase a Collectible, you (a) agree to pay the price for such Collectible as set forth in the applicable Service, together with any charges necessary to the fulfillment of the NFTs (including but not limited to any required gas fees) in connection with your purchase; and (b) authorize us and/or a third-party platform or system that fulfills payments for NFTs to charge your credit card, transact with your digital wallet, or other payment method for the Full Purchase Amount.</li>
              <li>You are solely responsible for any and all sales, use, value-added and other taxes, duties, and assessments (except taxes on our net income) now or hereafter claimed or imposed by any governmental authority associated with a Transaction.</li>
              <li>All fees and charges are payable in accordance with payment terms in effect at the time the fee or the charge becomes payable. Orders will not be processed until payment has been received in full, and any holds on your account by any payment processor are solely your responsibility. Your order may be suspended or cancelled for any reason, including if the payment method cannot be verified, is invalid or is otherwise not acceptable.</li>
              <li>Unless otherwise noted, all currency references displayed on the Platform are in Ethereum, and any correlated US dollar or any other currency displayed is meant as guidance to the estimated conversion price but is not binding on the Transaction.</li>
              <li>You represent and warrant that you have the legal right to use the payment method you provide to a third-party platform or system that fulfills payments for NFTs, including, without limitation, any credit card you provide when completing a transaction.</li>
            </ol>
          </li>
          <li>Upon purchasing a Collectible, the associated NFT will appear in your RareMint portfolio and corresponding External Wallet. You will see a record of your Transactions on the applicable blockchain ledger. You acknowledge and understand that your Ethereum public address will be made publicly visible whenever you engage in a Transaction.</li>
          <li>You acknowledge and agree that all information you provide with regards to an NFT transaction, including, without limitation, cryptocurrency, credit card or other payment information as the Platform may accept through a third-party platform or system from time-to-time, is accurate, current and complete.</li>
          <li>With the exception of the initial sale of each Collectible, RareMint is not a party to any Transaction. Notwithstanding the foregoing, you acknowledge that RareMint may impose a fee (sometime referred to as a royalty) on any sales of a Collectible after its initial purchase, and regardless whether such secondary sale occurs on the Platform or on some other platform. The fee structure will be disclosed on the Platform.</li>
          <li>We may, at our sole discretion, terminate, suspend or restrict your access to the Platform if there is reasonable suspicion by us that that the Collectible has been or will be used for any illegal, fraudulent, or unauthorized purposes.</li>
        </ol>
        <h3>8. OWNERSHIP OF COLLECTIBLES.</h3>
        <ol>
          <li>For every Collectible, RareMint is the initial owner of the Collectible. RareMint may promote and offer any Collectible for sale via the Platform.</li>
          <li>
            The purchaser of a Collectible does not acquire any intellectual property or other rights to any content, materials, art, design, and drawings (in any form or medium, including, without limitation, video or photographs) (collectively, “NFT Content”) referenced by a Collectible or the Physical Asset associated with an Asset-Backed NFT.
            <ol>
              <li>When you purchase a NFT, you own the NFT but you do not own any intellectual property rights in the NFT Content except for the license grants expressly set forth in Section 9 herein.</li>
              <li>
                If the NFT Content incidentally displays intellectual property not owned by RareMint (“Third-Party IP”)—e.g., sports team logos, athlete names—you understand and agree as follows:
                <ol>
                  <li>your purchase of the Collectible does not confer any right or license to use such Third-Party IP in any way except as incorporated in the NFT Content, and subject to the license and restrictions contained herein;</li>
                  <li>to the extent that we inform you of any additional restrictions on your use of the NFT Content, you will be responsible for complying with all such restrictions from the date that you receive the notice, and failure to do so will be deemed a breach of the license contained herein; and</li>
                  <li>Asset-Backed NFTs are not affiliated or associated with, sponsored or endorsed by, offered under license from, or officially connected to any third-party, including but not limited to any sports league, sports team, athlete, brand, or any subsidiaries or affiliates of any of them. Any third-party trademarks, service marks, trade names, logos, slogans, names, or other source identifiers or the name, voice, signature, or other likeness of any individual that may be incidentally displayed or used in Asset-Backed NFTs are all the property of the applicable third-party. Please visit the applicable brand's website for more information on official brand products.</li>
                </ol>
              </li>
              <li>When you buy a Collectible, you will retain the ability to transfer the Collectible to other parties. You may resell Asset-Backed NFTs and Digital-Only NFTs on an applicable blockchain, provided that any subsequent purchase of your NFT will also be subject to these Terms and may include a secondary sale fee, paid in most cases by the seller.</li>
            </ol>
          </li>
        </ol>
        <h3>CONTENT LICENSE.</h3>
        <ol>
          <li>
            Subject to your compliance with these Terms, RareMint hereby grants you a worldwide, non-exclusive, non-transferable, royalty-free license to use and display the NFT Content for each Collectible you purchase for so long as you are the valid owner and holder of the Collectible, solely for the following purposes:
            <ol>
              <li>for your own personal, non-commercial use;</li>
              <li>for listing on a marketplace that permits the purchase and sale of NFTs, provided that the marketplace cryptographically verifies each NFT owner's rights to display the NFT Content to ensure that only the actual owner can display the NFT Content; or</li>
              <li>as part of a third-party website or application that permits the inclusion, involvement, or display of NFTs for non-commercial purposes, provided that (A) the website or application cryptographically verifies each NFT owner's rights to display the NFT Content to ensure that only the actual owner can display the NFT Content, (B) the website or application prevents other users from downloading, saving, or otherwise creating copies of the NFT Content, and (C) the NFT Content is no longer visible once the owner of the NFT leaves the website or application.</li>
            </ol>
          </li>
          <li>
            You may not, nor will you permit any third party to, do or attempt to do any of the following without RareMint's (or, as applicable, our licensors') express prior written consent in each case:
            <ol>
              <li>modify the NFT Content in any way, including, without limitation, copying, modifying, editing, reverse engineering, decompiling, disassembling, or creating derivative works of any part of the Collectible or the metadata, shapes, designs, drawings, attributes, or color schemes;</li>
              <li>use the NFT Content to advertise, market, or sell any product or service other than the Collectible itself;</li>
              <li>use the NFT Content in connection with images, videos, or other forms of media that depict hatred, intolerance, violence, cruelty, or anything else that could reasonably be found to constitute hate speech or otherwise infringe upon the rights of others;</li>
              <li>sell, distribute for commercial gain (including, without limitation, giving away in the hopes of eventual commercial gain), or otherwise commercialize merchandise that includes, contains, or consists of the NFT Content;</li>
              <li>attempt to trademark, copyright, or otherwise acquire additional intellectual property rights in or to the NFT Content; or</li>
              <li>otherwise utilize the NFT Content for your or any third party's commercial benefit.</li>
            </ol>
          </li>
          <li>RareMint does not own, and therefore does not grant any license in, the Third-Party IP embodied in any Physical Asset. All rights other than those applicable to the owner of the Physical Asset are expressly reserved to their respective owners.</li>
        </ol>
        <h3>10. PURCHASES MADE FOR CONSUMPTIVE USE; NO INVESTMENT ADVICE</h3>
        <p>You acknowledge and affirm that you are purchasing NFTs, whether through the Platform or through a third-party platform, for purposes of acquiring digital collectibles and not for any investment or speculative purposes. Any economic benefit that may be derived from appreciation in the value of the NFT is incidental to obtaining it for its collectible purpose. RareMint does not provide investment, tax, or legal advice, or any other sort of advice, nor does RareMint broker NFT trades or trading in any other assets traded on the Service on your behalf. All transfers of NFTs or any other assets on the Service are based on the parameters of your instructions via the Services, and you are solely responsible for your actions and to conduct your own due diligence.</p>
        <h3>11. ASSUMPTION OF THE RISK.</h3>
        <p>You expressly understand and agree that:</p>
        <ol>
          <li>All use of the Services is at your own risk, and you are solely responsible for determining the level of risk involved. RareMint is not responsible for any losses you may suffer as a result of any drop in value or other aspects of the sale or purchase of any Collectible.</li>
          <li>We cannot guarantee that any Collectibles purchased or acquired by you will retain their original value or will have any particular value. You understand that the value of sports memorabilia is inherently subjective, and factors occurring outside of the Platform may materially impact the value and desirability of any particular Collectible.</li>
          <li>You assume all risk associated with the use and value of NFTs. NFTs are subject to volatility, and fluctuations in the price of cryptocurrency can also materially and adversely affect NFT prices. You acknowledge that you fully understand this subjectivity and volatility and that you may lose money.</li>
          <li>Blockchain technologies and NFTs are subject to many legal and regulatory uncertainties, and the Platform, NFTs, and Collectibles could be adversely impacted by one or more regulatory, or legal inquiries, actions, suits, investigations, claims, fines or judgments, which could materially adversely affect the development of the Services and the utility of NFTs.</li>
          <li>RareMint does not control the public blockchains that you are interacting with, and we do not control certain smart contracts and protocols that may be integral to your ability to complete transactions on these public blockchains. Additionally, blockchain transactions are irreversible and RareMint has no ability to reverse any transactions on the blockchain.</li>
          <li>There are risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your electronic wallet.</li>
          <li>Cryptocurrencies are not backed by any government, central bank, physical value, or another guarantee. Their values and liquidity can materially fluctuate up and down due to market activity and sentiment, public and regulator sentiment, legislation, regulatory and governmental steps taken in relation to crypto-assets generally, or specifically, and other factors outside of the control of users.</li>
          <li>There are risks associated with purchasing items associated with content created by third parties through peer-to-peer transactions, including but not limited to, the risk of purchasing counterfeit items, mislabeled items, items that are vulnerable to metadata decay, items on smart contracts with bugs, and items that may become untransferable. You are solely responsible for performing sufficient research before making any decisions to sell, obtain, transfer, or otherwise interact with any Collectibles or sellers.</li>
          <li>RareMint provides its Services on an “AS IS” and “AS AVAILABLE” basis. RareMint expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, (A) the implied warranties of merchantability, title, fitness for a particular purpose, and non-infringement, and (B) any warranties that the Services will be without error or viruses, worms, or other harmful software or hardware. If you are dissatisfied with any portion of the Services, or with any of these Terms, your sole and exclusive remedy is to discontinue using the Services.</li>
          <li>RareMint is not liable for any defects in, unavailability of, changes to, or acts or omissions of liable for any acts or omissions of the provider of any third-party service you use in connection with the Service, including but not limited to providers of Internet service, External Wallets, or blockchain networks.</li>
          <li>The Ethereum network may be subject to sudden changes in operating rules, and third parties may, from time to time, fork the Ethereum blockchain and implement changes in the operating rules or other features that might result in multiple versions of Ethereum and, possibly, more than one version of the NFT. This may affect the value and the function of the initial NFT and we can temporarily suspend our services while we determine, at our sole and absolute discretion, which network to support. Such networks and forks are outside of our control and we can decide, at our sole and absolute discretion, to abandon or otherwise not support the initial or the copy of the NFT. We may, at our sole and absolute discretion, obtain and retain the unsupported NFTs.</li>
          <li>RareMint will not be able to restore or issue any refund in respect of any Collectibles due to lost or stolen private cryptocurrency or External Wallet keys. If you are not able to access or use a Collectible due to loss or theft of the corresponding private key or otherwise, you will be unable to exercise your rights with respect to such Collectible. See details on the Platform as to any processes in place to assist you (which are at our discretion).</li>
          <li>Except for NFT Content created or commissioned by RareMint, RareMint shall not be liable for any errors, misrepresentations, or omissions in, of, and about, the underlying NFT Content, nor for the availability of the NFT Content. RareMint shall not be liable for any losses, injuries, or damages from the purchase, inability to purchase, display, or use of the underlying NFT Content.</li>
          <li>There can be no guarantee or assurance of the uniqueness, originality or quality of any Collectible. You have no recourse or rights against us in relation to the existence of similar or identical works, or in relation to the infringement of any third-party rights, except to the extent the intellectual property allegedly infringed was created or commissioned by RareMint.</li>
          <li>There is a risk that RareMint may be obligated to take down listings from the Platform if it has received a Digital Millennium Copyright Notice (“DMCA Notice”). RareMint may also be obligated to serve a DMCA Notice to its IPFS service provider. If this occurs, the NFT representing the Collectible may no longer reference the NFT Content. Collectibles linked to images subject to a DMCA Notice may subsequently reference an invalid file location or a file that no longer exists.</li>
          <li>No employee or agent of RareMint, and no information on the Platform, can create any warranty not expressly set forth in the Terms or the Privacy Policy nor waive any disclaimer or waiver expressly set forth in the Terms or the Privacy Policy.</li>
        </ol>
        <h3>12. DMCA NOTICES</h3>
        <p>If you believe that your work was copied or posted on the Platform in a way that constitutes copyright infringement, please contact us at the address below:</p>
        <p>RareMint Limited<br/>Attn: Legal Department<br/> Trinity Chambers, PO Box 4301,<br/> Road Town, Tortola, British Virgin Islands, VG1110</p>
        <p>Your notice must include the following information: A description of the copyrighted work you claim has been infringed;</p>
        <ol>
          <li>If you do not own the copyrighted work, your physical or digital signature as a person authorized to act on behalf of the copyright owner;</li>
          <li>A description of where the material you claim is infringing is located on the Platform;</li>
          <li>Information reasonably sufficient to permit RareMint to contact you, such as an address, telephone number, or email address;</li>
          <li>A statement that you have a good faith belief that the disputed use of the material is not authorized by the copyright owner, its agent, or the law; and</li>
          <li>A statement by you, made under penalty of perjury, that the information in your notice is</li>
          <li>accurate and that you are the copyright owner or are authorized to act on behalf of the copyright owner.</li>
        </ol>
        <p>RareMint will respond to allegations of copyright violations in accordance with the Digital Millennium Copyright Act (“DMCA”). If RareMint receives a valid DMCA notice, we will take down the offending content. RareMint then will take reasonable steps so that a counter-notice may be filed. RareMint generally will restore the content if there is a valid counter-notice, unless we are notified that a legal action has been filed seeking a court order to restrain the alleged infringing activity. RareMint may provide copies of any DMCA notices to interested parties or to third parties. DMCA notices are not subject to RareMint's Privacy Policy. RareMint accommodates and does not interfere with standard technical measures used by copyright owners to protect their materials.</p>
        <h3>13. INDEMNIFICATION.</h3>
        <ol>
          <li>
            By You. You agree to defend, indemnify, and hold harmless RareMint, its affiliates, and its and their respective managers, directors, advisors, officers, employees, and agents from and against all claims, demands, offers of license, liabilities, damages, losses, costs, and expenses, including attorneys' fees and costs, arising out of or related to:
            <ol>
              <li>your breach of the Terms of Service or the Privacy Policy;</li>
              <li>your use of the Platform;</li>
              <li>your purchase of Collectibles;</li>
              <li>any other person using your account, or any of your personal information, to access or use the Platform, whether with your permission or not;</li>
              <li>your violation of any law or regulation; and/or</li>
              <li>your infringement of any intellectual property or other rights of any other person or entity, except to the extent the intellectual property allegedly infringed was created or commissioned by RareMint.</li>
            </ol>
          </li>
          <li>By RareMint. RareMint agrees to defend, indemnify, and hold harmless your, your affiliates, and your and their respective managers, directors, officers, employees, and agents, from and against all claims, demands, offers of license, liabilities, damages, losses, costs, and expenses, including attorneys' fees and costs, arising out of or related to your infringement of any intellectual property or other rights of any other person or entity, only to the extent the intellectual property allegedly infringed was created or commissioned by RareMint.</li>
        </ol>
        <h3>14. LIMITATION OF LIABILITY; WAIVER</h3>
        <p>YOU UNDERSTAND AND AGREE THAT RAREMINT AND ITS AFFILIATES AND LICENSORS WILL NOT BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES WHICH YOU MAY INCUR, HOWSOEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT LIMITATION, ANY LOSS OF PROFITS (WHETHER INCURRED DIRECTLY OR INDIRECTLY), LOSS OF GOODWILL OR BUSINESS REPUTATION, LOSS OF DATA, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, DIMINUTION OF VALUE OR ANY OTHER INTANGIBLE LOSS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
        <p>EXCEPT FOR CLAIMS FOR INDEMNIFICATION PURSUANT TO SECTION 13, OUR LIABILITY TO YOU WILL BE LIMITED TO (A) WHERE RAREMINT IS THE SELLER OF A COLLECTIBLE, THE PURCHASE PRICE OF PAID FOR THAT COLLECTIBLE; AND (B) IN ALL OTHER CASES, FIVE HUNDRED US DOLLARS (US$500.00).</p>
        <p>YOU ACKNOWLEDGE AND AGREE THAT WE HAVE MADE THE SERVICES AVAILABLE TO YOU AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE REPRESENTATIONS AND WARRANTIES, DISCLAIMERS AND LIMITATIONS OF LIABILITY SET FORTH HEREIN, WHICH REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN RAREMINT AND YOU AND FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN US AND YOU.</p>
        <h3>15. INTELLECTUAL PROPERTY RIGHTS.</h3>
        <p>The information and other content on or presented to you through the Platform may be protected by various laws relating to intellectual property, including, but not limited to, copyrights and trademarks. You may not modify, distribute, copy, reproduce, or create derivative works based on the Site, the information or other content on the Site, or any Collectible, in whole or in part. You may not reverse engineer, decompile, or disassemble the Platform, NFT, or its underlying technologies, except to the extent the foregoing restriction is expressly prohibited by applicable law. RareMint holds the copyright to those portions of the Platform it owns and reserves all its rights. RareMint's trademarks, trade names, service marks, logos, and service names are marks that belong to RareMint or its licensors, and you may not display them or use them in any manner without the express prior written permission of RareMint.</p>
        <h3>16. THIRD-PARTY WEBSITES.</h3>
        <p>The Site may include materials from and links to websites operated by parties other than RareMint. RareMint provides such information for general informational purposes only and does not endorse or approve the information on those sites, the entities sponsoring those sites, or those entities' products or services. As RareMint has no control over these third-party websites or resources, you agree RareMint will not be responsible or liable for any content, statements, representations, advertising, products, services, or other materials on or available from such sites or resources. You also agree RareMint will not be responsible or liable, directly or indirectly, for, and waive all claims against RareMint arising out of, any damage or loss you may suffer by using or relying on any such content, statements, representations, advertising, products, services, or other materials.</p>
        <h3>17. SOLE BENEFIT.</h3>
        <p>The Terms are for the benefit of RareMint, its affiliates, and its and their respective managers/directors, officers, employees, and agents. There are no other intended third-party beneficiaries. RareMint owes no duty to you to enforce these Terms, you may not rely on RareMint to enforce these Terms, and RareMint will not be liable to you if it fails to enforce these Terms.</p>
        <h3>18. WAIVER AND RELEASE OF CLAIMS.</h3>
        <p>You hereby release RareMint, its affiliates, and its and their respective managers/directors, officers, employees, and agents, from any and all claims that may arise as a result of your use of the Services, your inability to use the Services, or any content on the Site. If you reside in California or if the laws of California otherwise apply to you, you hereby waive California Civil Code Section 1542, which states: “a general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor.” You acknowledge you have carefully read this Paragraph 18 and fully understand that it is a release of liability. Because some jurisdictions may not allow the exclusion, limitation, or waiver of liability as set forth in this Section and the preceding Section, some of these provisions may not apply to you if prohibited by law.</p>
        <h3>19. ARBITRATION AND CLASS ACTION WAIVER.</h3>
        <ol>
          <li><u>Informal Process First.</u> You agree that in the event of any dispute between you and RareMint, you will first contact RareMint and make a good faith sustained effort to resolve the dispute before resorting to more formal means of resolution, including without limitation, any court action.</li>
          <li><u>Arbitration Agreement.</u> After the informal dispute resolution process, any remaining dispute, controversy, or claim (collectively, “Claim”) relating in any way to your use of RareMint's services, Platform NFTs and/or products, including the Services, will be resolved by arbitration, including threshold questions of arbitrability of the Claim, except as permitted herein. You and RareMint agree that any Claim will be settled by final and binding arbitration, using the English language, administered by JAMS under its Comprehensive Arbitration Rules and Procedures and the JAMS Consumer Minimum Standards (together, the “JAMS Rules”) then in effect (those rules are deemed to be incorporated by reference into this section, and as of the date of these Terms). Arbitration will be handled by a sole arbitrator in accordance with the JAMS Rules. Judgment on the arbitration award may be entered in any court that has jurisdiction. You have a right to have the arbitration conducted via telephone or videoconference, or as an in-person hearing in your hometown area (if you live in the United States) or another location that is reasonably convenient to you. This arbitration agreement shall survive the termination of your relationship RareMint.</li>
          <li><u>Waiver of Class Actions and Class Arbitrations.</u> You and RareMint agree that each party may bring Claims against the other party only in an individual capacity, and not as a plaintiff or class member in any purported class or representative proceeding, including without limitation federal or state class actions, or class arbitrations. Accordingly, under the arbitration procedures outlined in this section, an arbitrator shall not combine or consolidate more than one party's claims without the written consent of all affected parties to an arbitration proceeding. Without limiting the generality of the foregoing, you and RareMint agree that no dispute shall proceed by way of class arbitration without the written consent of all affected parties.</li>
          <li><u>Costs of Arbitration.</u> Payment for any and all reasonable JAMS filing, administrative and arbitrator fees will be in accordance with the JAMS Rules. If the value of your claim does not exceed $10,000, RareMint will pay for the reasonable filing, administrative and arbitrator fees associated with the arbitration, unless the arbitrator finds that either the substance of your claim or the relief sought was frivolous or brought for an improper purpose, except that if you have initiated the arbitration claim, you will still be required to pay the lesser of $250 or the maximum amount permitted under the JAMS Rules for arbitration claims initiated by you. You are still responsible for all additional costs that you incur in the arbitration, including without limitation, fees for attorneys or expert witnesses.</li>
          <li><u>Opt-Out.</u> You have the right to opt-out and not be bound by the arbitration and waiver of class provisions set forth in these Terms by sending written notice of your decision to opt-out to support@raremint.com or to our mailing address listed in the “How to Contact Us” section of these Terms. The notice must be sent to RareMint within thirty (30) days of your registering to use the Services or agreeing to these Terms (or if this Section 19, pertaining to arbitration, is materially amended hereafter, within 30 days of such amendment being effective), otherwise you shall be bound to arbitrate disputes in accordance with these Terms, and the notice must specify your name and mailing address. If you opt-out of these arbitration provisions, RareMint also will not be bound by them.</li>
          <li><u>Exceptions.</u> Notwithstanding anything in these Terms to the contrary, you may instead assert your Claim in “small claims” court, but only if your Claim qualifies, your Claim remains only in such court, and your Claim remains on an individual, non-representative and non-class basis. Further, you and RareMint will have the right to bring an action in a court of proper jurisdiction for injunctive or other equitable or conservatory relief, or if the Claim relates to intellectual property infringement or misappropriation.</li>
          <li><u>Our Right to Seek Injunctive Relief.</u> Nothing in these Terms will prevent RareMint from seeking injunctive relief in any court of competent jurisdiction as necessary to protect its proprietary interests. By way of example and not limitation, you acknowledge and agree that in the event of a breach or threatened violation of our intellectual property rights and confidential and proprietary information by you, we will suffer irreparable harm and will therefore be entitled to seek any interim, equitable, provisional, or injunctive relief that is necessary to protect our rights and property pending the outcome of the arbitration referenced above.</li>
        </ol>
        <h3>20. GOVERNING LAW AND JURISDICTION.</h3>
        <p>These Terms are governed by the laws of the British Virgin Islands, except that there may be certain mandatory applicable laws of your country or region that apply for your benefit and protection in addition to or instead of certain provisions of British Virgin Islands law. Except as set forth in Section 19, you agree that any dispute between you and us regarding these Terms or the Services will only be dealt with by the British Virgin Island courts.</p>
        <h3>21. CONTENT OF THE SERVICES.</h3>
        <ol>
          <li>RareMint reserves the right to make corrections, changes, or improvements to the content on the Services. The information on the Services may contain inaccuracies or typographical errors. RareMint will not be obligated to honor transactions affected by such inaccuracies or errors. RareMint, its affiliates, and its Contractors do not warrant the accuracy, completeness, usefulness, or availability of that information and will not be responsible for any errors, omissions, or other problems with that information. If the accuracy, completeness, or availability of that information is important to you, you should independently verify or source all such information.</li>
          <li>From time to time, we may, in our sole discretion, include certain test or beta features in the Services (“Beta Features”). Your use of any Beta Feature is voluntary. You agree that once you use a Beta Feature, Your content or data may be affected such that you may be unable to revert back to a prior non-beta version of the same or similar feature. Additionally, if such reversion is possible, you may not be able to return or restore data created within the Beta Feature back to the prior non-beta version. The Beta Features are provided on an “as is” basis and may contain errors or inaccuracies that could cause failures, corruption or loss of data and information from any connected device. You acknowledge and agree that all use of any Beta Feature is at your sole risk.</li>
        </ol>
        <h3>22. MISCELLANEOUS</h3>
        <ol>
          <li><u>Changes to the Terms.</u> RareMint may add to, delete from, revise, or otherwise modify all or part of the Terms and the Privacy Policy at any time and in our sole discretion. If we make material changes to these Terms, we will use reasonable efforts to provide notice of such changes, such as by providing notice through the Services or updating the “Last Updated” date at the beginning of these Terms. You can review the most current version of the Terms and the Privacy Policy on the website at <Link to="/">www.RareMint.com</Link> .By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference effective as of the date these Terms are updated. It is your sole responsibility to review the Terms from time to time to view such changes and to ensure that you understand the terms and conditions that apply when you access or use the Services.</li>
          <li><u>Waiver.</u> RareMint's failure to exercise or enforce any right or provision of the Terms will not waive its right to subsequently enforce that right or provision unless RareMint acknowledges and agrees to the wavier of its rights in writing.</li>
          <li><u>Severability.</u> If any provision of the Terms or the Privacy Policy is found to be invalid or unenforceable, you nevertheless agree that (A) all other provisions of the Terms and the Privacy Policy will remain in full force and effect, and (B) an arbitrator should endeavor to give effect to the substance of the invalid provision to the full extent permitted by law.</li>
          <li><u>Headings.</u> The section headings and sub-headings contained in the Terms and the Privacy Policy are for convenience only and have no legal or contractual effect.</li>
          <li><u>How to Contact Us.</u> You may contact us regarding the Services or these Terms at: Trinity Chambers, PO Box 4301, Road Town, Tortola, British Virgin Islands, VG1110 or by e-mail at <a href="mailto:support@raremint.com">support@raremint.com</a>.</li>
        </ol>
      </Content>
    </Container>
  )
}
